import {
  SignInButton,
  SignOutButton,
  UserButton,
  useUser,
} from "@clerk/nextjs";
import { GeneratePrimeOptionsArrayBuffer } from "crypto";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex">
      <img
        src={user.profileImageUrl}
        alt="ProfileImage"
        className="h-14 w-14 rounded-full"
      />
    </div>
  );
};

export default function Home(props) {
  const user = useUser();
  /*
  const hello = api.post.postList.useQuery();
  console.log(hello)
  */
  const { data } = api.post.getAll.useQuery();
  console.log(data);

  return (
    <>
      <Head>
        <title>Creating T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <nav className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="my-2 me-2 ms-auto ">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && (
              <>
                <div className="my-2 me-auto ms-2">
                  <CreatePostWizard />
                </div>
                <div className="my-2 me-2 ms-auto">
                  <SignOutButton />
                </div>
              </>
            )}
          </nav>
          <div className="w-full">
            {data?.map((item) => {
              return (
                <div
                  key={item.id}
                  className="border-slate-400S flex border-b p-8"
                >
                  <span className="text-center">{item.content}</span>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}
