import { SignInButton, SignOutButton, UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();

  if(!user) return null

  return (
  <div className="flex">
    <img
      src={user.profileImageUrl} 
      alt="ProfileImage" 
      className="h-14 w-14 rounded-full"
    />
  </div>
  );
}


export default function Home() {
  const user = useUser()
  /*
  const hello = api.post.postList.useQuery();
  console.log(hello)
  */
  const {data} = api.post.getAll.useQuery();
  console.log(data)
 
  return (
    <>
      <Head>
        <title>Creating T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x border-slate-400">
          <nav className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && 
              <div className="me-2 ms-auto my-2 ">
                <SignInButton />
              </div>
            }
            {
              !!user.isSignedIn &&
                <>
                  <div className="ms-2 me-auto my-2">
                    <CreatePostWizard />
                  </div>
                  <div className="me-2 ms-auto my-2">
                    <SignOutButton />
                  </div>
                </>
            }
          </nav>
          <div className="w-full">
              {
                data?.map((item)=>{
                  return <div key={item.id} className="flex p-8 border-b border-slate-400S">
                      <span  className="text-center">
                        {item.content}
                      </span>
                  </div>
                })
              }
          </div>
        </div>
      </main>
    </>
  );
}
